
const Mission = () => {
  return (
    <div>
        <h3 className="text-4xl mb-4 text-orange-800">Mission</h3>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam officia temporibus nulla vero blanditiis, vitae odio facere quaerat, fugit aliquid sit dignissimos illo omnis cum a? Deleniti accusantium voluptatum fuga cum reprehenderit! Labore odit maiores minima, eveniet cum repellendus harum officia ex iusto at temporibus animi corporis possimus optio ea! Voluptatum asperiores, in facere a sequi neque eveniet consequatur fugit ipsa explicabo saepe animi deleniti! Quo cumque pariatur alias magnam quae aperiam numquam, omnis sed repudiandae illum natus at? Quia quas dicta delectus provident pariatur rerum architecto consectetur fugiat minima sapiente dolores sint tempora eaque quibusdam dolore, nostrum tempore qui atque suscipit iste alias veniam officiis quod! Rerum eaque ex cum quibusdam quam ullam et vitae itaque. Illum earum et hic. Voluptate nemo beatae ratione impedit eveniet praesentium corrupti, vitae deleniti quaerat dolor nihil saepe vero asperiores doloribus animi delectus. Reprehenderit ullam ab repellat nesciunt quasi voluptates eum odio quisquam delectus voluptatum error asperiores nemo vitae cum incidunt omnis fuga praesentium, consequuntur laudantium cumque placeat minus unde? Voluptate earum quod consequuntur eligendi consectetur laudantium harum, unde error qui dolorem blanditiis maxime tenetur ex tempore amet, voluptates dolor fugit? Enim totam cumque incidunt nemo, labore fuga, minima beatae corrupti fugit debitis tenetur autem porro fugiat quis nobis. Veniam quam consequatur ullam cupiditate, numquam repellendus soluta inventore quisquam pariatur animi alias assumenda asperiores minima laboriosam accusantium, voluptatem incidunt obcaecati nihil vitae quod! Aut vero perferendis, voluptatibus illum hic cumque autem mollitia maiores obcaecati optio neque, minus a iure eveniet nam ipsam nisi.</p>
    </div>
  )
}

export default Mission