import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='flex min-h-screen flex-col items-center justify-between p-24'>
      <body className={inter.className}>
        <nav>
          <ul className='flex gap-6 text-4xl mb-4'>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
          
          </ul>
        </nav>
   
        {children}
        </body>
    </html>
  )
}
